apiVersion: v1
kind: Pod
metadata: 
  name: pod-with-rediness
  labels:
    app: pod-with-rediness-labels
  namespace: dev  
spec:
  containers:
  - name: nginx
    image: nginx    
    ports:
      - containerPort: 8080
    readinessProbe:
      httpGet: 
        path: /
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 5
    livenessProbe:
      httpGet:
        path: /
        port: 80