apiVersion: v1
kind: Pod
metadata:
  name: rest-ms-pod
  labels: 
     app: my-rest-ms
  namespace: cellar
spec:
 containers:
 - image: docker.io/mauriziorizzo89/rest-ms:1.0.0
   name: rest-ms-container
