apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-statefulset
  labels:
    app: mysql
spec:
  template:
    metadata:
       labels:
         app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql-h #heandless Service
  podManagementPolicy: Parallel #avvia le repliche in parallelo e non una dopo l'altra
