apiVersion: apps/v1
kind: Deployment
metadata: 
   name: rest-ms-deployment
   namespace: cellar
spec:
   replicas: 3
   strategy: 
     type: RollingUpdate
   selector:
      matchLabels:
        app: my-rest-ms
   template:
      metadata:
        name: rest-ms-pod
        labels: 
          app: my-rest-ms
        namespace: cellar  
      spec:
        containers:
        - image: docker.io/mauriziorizzo89/rest-ms:1.0.0
          name: rest-ms-container
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          livenessProbe:
            initialDelaySeconds: 10
            failureThreshold: 5
            periodSeconds: 20
            timeoutSeconds: 10
            httpGet:
              path: /actuator/health
              port: 8080
          readinessProbe:
            initialDelaySeconds: 10
            failureThreshold: 5
            periodSeconds: 20
            timeoutSeconds: 10
            httpGet:
              path: /actuator/health
              port: 8080    
