apiVersion: v1
kind: Namespace
metadata:
  name: dev-core-ms
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-core-ms
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitor-tools
---
apiVersion: v1
kind: Namespace
metadata:
   name: cellar
